openapi: 3.0.1
info:
  title: API Demo
  version: "1.0"
servers:
- url: /v1
paths:
  /patent/trend1:
    post:
      summary: 专利趋势1
      operationId: patent_trend1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Trend1Req'
        required: true
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trend1Res'
        "400":
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
      x-openapi-router-controller: swagger_server.controllers.default_controller
    options:
      summary: CORS support for 专利趋势1
      operationId: patent_trend1_options
      responses:
        "200":
          description: CORS preflight request successful
          content: {}
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /patent/trend2:
    post:
      summary: 专利趋势2
      operationId: patent_trend2
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Trend2Req'
        required: true
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trend2Res'
        "400":
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
      x-openapi-router-controller: swagger_server.controllers.default_controller
    options:
      summary: CORS support for 专利趋势2
      operationId: patent_trend2_options
      responses:
        "200":
          description: CORS preflight request successful
          content: {}
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /patent/applicant:
    post:
      summary: 申请人分析
      operationId: patent_applicant
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApplicantReq'
        required: true
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicantRes'
        "400":
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
      x-openapi-router-controller: swagger_server.controllers.default_controller
    options:
      summary: CORS support for 申请人分析
      operationId: patent_applicant_options
      responses:
        "200":
          description: CORS preflight request successful
          content: {}
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /patent/area:
    post:
      summary: 地域分析
      operationId: patent_area
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AreaReq'
        required: true
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AreaRes'
        "400":
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
      x-openapi-router-controller: swagger_server.controllers.default_controller
    options:
      summary: CORS support for 地域分析
      operationId: patent_area_options
      responses:
        "200":
          description: CORS preflight request successful
          content: {}
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /patent/type:
    post:
      summary: 类型分析
      operationId: patent_type
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TypeReq'
        required: true
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TypeRes'
        "400":
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
      x-openapi-router-controller: swagger_server.controllers.default_controller
    options:
      summary: CORS support for 类型分析
      operationId: patent_type_options
      responses:
        "200":
          description: CORS preflight request successful
          content: {}
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /patent_report/save:
    post:
      summary: 报告保存
      operationId: patent_report_save
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatentReportReq'
        required: true
      responses:
        "200":
          description: success
          content: {}
        "400":
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
      x-openapi-router-controller: swagger_server.controllers.default_controller
    options:
      summary: CORS support for 报告保存
      operationId: patent_report_save_options
      responses:
        "200":
          description: CORS preflight request successful
          content: {}
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /patent_report_detail/save:
    post:
      summary: 报告详情保存
      operationId: patent_report_detail_save
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatentReportDetailReq'
        required: true
      responses:
        "200":
          description: success
          content: {}
        "400":
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
      x-openapi-router-controller: swagger_server.controllers.default_controller
    options:
      summary: CORS support for 报告详情保存
      operationId: patent_report_detail_save_options
      responses:
        "200":
          description: CORS preflight request successful
          content: {}
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /patent/technology:
    post:
      summary: 技术构成分析
      operationId: patent_technology
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TechnologyReq'
        required: true
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TechnologyRes'
        "400":
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
      x-openapi-router-controller: swagger_server.controllers.default_controller
    options:
      summary: CORS support for 技术构成分析
      operationId: patent_technology_options
      responses:
        "200":
          description: CORS preflight request successful
          content: {}
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /patent/concentration:
    post:
      summary: 集中度分析
      operationId: patent_concentration
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConcentrationReq'
        required: true
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConcentrationRes'
        "400":
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
      x-openapi-router-controller: swagger_server.controllers.default_controller
    options:
      summary: CORS support for 集中度分析
      operationId: patent_concentration_options
      responses:
        "200":
          description: CORS preflight request successful
          content: {}
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /report/list:
    post:
      summary: 报告列表
      operationId: report_list
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListReq'
        required: true
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListRes'
        "400":
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
      x-openapi-router-controller: swagger_server.controllers.default_controller
    options:
      summary: CORS support for 报告列表
      operationId: report_list_options
      responses:
        "200":
          description: CORS preflight request successful
          content: {}
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /report/detail:
    post:
      summary: 报告详情
      operationId: report_detail
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DetailReq'
        required: true
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailRes'
        "400":
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
      x-openapi-router-controller: swagger_server.controllers.default_controller
    options:
      summary: CORS support for 报告详情
      operationId: report_detail_options
      responses:
        "200":
          description: CORS preflight request successful
          content: {}
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /report/delete:
    post:
      summary: 删除报告
      operationId: report_delete
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteReq'
        required: true
      responses:
        "200":
          description: success
          content: {}
        "400":
          description: Invalid input
          content: {}
      x-codegen-request-body-name: body
      x-openapi-router-controller: swagger_server.controllers.default_controller
    options:
      summary: CORS support for 删除报告
      operationId: report_delete_options
      responses:
        "200":
          description: CORS preflight request successful
          content: {}
      x-openapi-router-controller: swagger_server.controllers.default_controller
components:
  schemas:
    Trend1Req:
      type: object
      properties:
        industry:
          type: string
        area:
          type: string
        applicant:
          type: string
        key:
          type: string
    Trend1Res:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Trend1Res_data'
      example:
        data:
          year: year
          num: 0
    Trend2Req:
      type: object
      properties:
        industry:
          type: string
        area:
          type: string
        applicant:
          type: string
        key:
          type: string
    Trend2Res:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Trend2Res_data'
      example:
        data:
          proportion: 1.4658129
          year: year
          apply_num: 6
          authorization_num: 0
    ApplicantReq:
      type: object
      properties:
        industry:
          type: string
        area:
          type: string
        applicant:
          type: string
        key:
          type: string
    ApplicantRes:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/ApplicantRes_data'
      example:
        data:
          num: 0
          applicant: applicant
    AreaReq:
      type: object
      properties:
        industry:
          type: string
        applicant:
          type: string
        key:
          type: string
    AreaRes:
      type: object
      properties:
        years:
          $ref: '#/components/schemas/AreaRes_years'
        areas:
          $ref: '#/components/schemas/AreaRes_areas'
      example:
        areas:
          area: area
          data:
            num: 0
        years:
          year: year
    TypeReq:
      type: object
      properties:
        industry:
          type: string
        applicant:
          type: string
        key:
          type: string
    TypeRes:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/TypeRes_data'
      example:
        data:
          num: 0
          type: type
    PatentReportReq:
      type: object
      properties:
        user_id:
          type: string
        key:
          type: string
        industry:
          type: string
        area:
          type: string
        applicant:
          type: string
    PatentReportRes:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/PatentReportRes_data'
      example:
        data:
          id: 0
          title: 报告标题
    PatentReportRes_data:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
      example:
        id: 0
    PatentReportDetailReq:
      type: object
      properties:
        report_id:
          type: string
        type:
          type: string
        sub_title:
          type: string
        content:
          type: string
        data:
          type: string
    PatentReportDetailRes:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/PatentReportDetailRes_data'
      example:
        data:
          id: 0
    PatentReportDetailRes_data:
      type: object
      properties:
        id:
          type: integer
      example:
        id: 0
    TechnologyReq:
      type: object
      properties:
        industry:
          type: string
        area:
          type: string
        applicant:
          type: string
        key:
          type: string
    TechnologyRes:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/TechnologyRes_data'
      example:
        data:
          num: 0
          class: class
    ConcentrationReq:
      type: object
      properties:
        industry:
          type: string
        area:
          type: string
        applicant:
          type: string
        key:
          type: string
    ConcentrationRes:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/ConcentrationRes_data'
      example:
        data:
          proportion: 0.8008282
          year: year
    ListReq:
      type: object
      properties:
        user_id:
          type: string
    ListRes:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/ListRes_data'
      example:
        data:
          update_time: update_time
          is_deleted: 1
          batch_id: 5
          id: 0
          title: title
          status: 6
    DetailReq:
      type: object
      properties:
        id:
          type: integer
    DetailRes:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/DetailRes_data'
      example:
        data:
          sub_title: sub_title
          is_deleted: 6
          data: data
          type: type
          content: content
          status: 0
    DeleteReq:
      type: object
      properties:
        ids:
          type: array
          items:
            type: integer
    Trend1Res_data:
      type: object
      properties:
        year:
          type: string
        num:
          type: integer
      example:
        year: year
        num: 0
    Trend2Res_data:
      type: object
      properties:
        year:
          type: string
        authorization_num:
          type: integer
        apply_num:
          type: integer
        proportion:
          type: number
          format: float
      example:
        proportion: 1.4658129
        year: year
        apply_num: 6
        authorization_num: 0
    ApplicantRes_data:
      type: object
      properties:
        applicant:
          type: string
        num:
          type: integer
      example:
        num: 0
        applicant: applicant
    AreaRes_years:
      type: object
      properties:
        year:
          type: string
      example:
        year: year
    AreaRes_areas_data:
      type: object
      properties:
        num:
          type: integer
      example:
        num: 0
    AreaRes_areas:
      type: object
      properties:
        area:
          type: string
        data:
          $ref: '#/components/schemas/AreaRes_areas_data'
      example:
        area: area
        data:
          num: 0
    TypeRes_data:
      type: object
      properties:
        type:
          type: string
        num:
          type: integer
      example:
        num: 0
        type: type
    TechnologyRes_data:
      type: object
      properties:
        class:
          type: string
        num:
          type: integer
      example:
        num: 0
        class: class
    ConcentrationRes_data:
      type: object
      properties:
        year:
          type: string
        proportion:
          type: number
          format: float
      example:
        proportion: 0.8008282
        year: year
    ListRes_data:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        update_time:
          type: string
        status:
          type: integer
        is_deleted:
          type: integer
        batch_id:
          type: integer
      example:
        update_time: update_time
        is_deleted: 1
        batch_id: 5
        id: 0
        title: title
        status: 6
    DetailRes_data:
      type: object
      properties:
        type:
          type: string
        sub_title:
          type: string
        content:
          type: string
        data:
          type: string
        status:
          type: integer
        is_deleted:
          type: integer
      example:
        sub_title: sub_title
        is_deleted: 6
        data: data
        type: type
        content: content
        status: 0
x-original-swagger-version: "2.0"

